server:
  port: 9000
# API Gateway configuration for routings and load balancing
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: watchlist-service
          uri: lb://watchlist-service
          predicates:
            - Path=/watchlist/**

        - id: dashboard-application
          uri: lb://dashboard-application
          predicates:
            - Path=/api/portfolios/**

        - id: portfolio-service
          uri: lb://portfolio-service
          predicates:
            - Path=/api/v1/userPortfolioInfo/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/transactions/**
